### PR TITLE
Add cross-env package

### PR DESCRIPTION
**Pull request by factoryal**
in package.json,
```js
    "maimai:fetch-images": "NODE_EXTRA_CA_CERTS='gsrsaovsslca2018.pem' ts-node src/maimai/fetch-images",
    "maimai:fetch-versions": "NODE_EXTRA_CA_CERTS='gsrsaovsslca2018.pem' ts-node src/maimai/fetch-versions",
    "maimai:fetch-intl-versions": "NODE_EXTRA_CA_CERTS='gsrsaovsslca2018.pem' ts-node src/maimai/fetch-intl-versions",
```
these scripts cannot be run on Windows terminal.

The `cross-env` package is required to resolve the problem.
npm script will have some changes -> 
```js
    "maimai:fetch-images": "cross-env NODE_EXTRA_CA_CERTS='gsrsaovsslca2018.pem' ts-node src/maimai/fetch-images",
    "maimai:fetch-versions": "cross-env NODE_EXTRA_CA_CERTS='gsrsaovsslca2018.pem' ts-node src/maimai/fetch-versions",
    "maimai:fetch-intl-versions": "cross-env NODE_EXTRA_CA_CERTS='gsrsaovsslca2018.pem' ts-node src/maimai/fetch-intl-versions",
```

Thanks.

### CODE REVIEW

**Comment by zetaraku** [comment]
Thank you for your contribution!

However, the project is assumed to be run under Unix-like environments so the npm scripts will be only written in bash.
The npm scripts in this project may use more bash-only features in the future, so introducing `cross-env` won't completely solve this problem.

If you are under Windows, I recommend using **Git Bash** brought by [Git](https://git-scm.com/) to run the scripts.
You can also configure Visual Studio Code to use Git Bash as the default shell.

See: https://stackoverflow.com/questions/44435697/change-the-default-terminal-in-visual-studio-code

If you still want to run the scripts in cmd or other shells, you can configure your npm to use the installed Git Bash to run npm scripts.

See: https://stackoverflow.com/questions/23243353/how-to-set-shell-for-npm-run-scripts-in-windows

I hope this solves your problem. Have a nice day!

**Comment by factoryal** [comment]
Hi.
Thanks for checking this request.

I fully understand your intention.
However, someone not expert on Node.js like me, might have some trouble while following the guide.
Would you add some comment on readme that the npm script works on bash? (or add bash in Prerequisites section)

**Comment by zetaraku** [comment]
Sure thing! Would add it later! :)

**Comment by factoryal** [comment]
I also THANK YOU for sharing great project.

I'll close this request.

**Pull request closed without merging**
